/:
    template: blog/overview.twig
    variables:
        title: Blog
        overviewTitle: programming
        posts: src/content/blog.yaml
        meta:
            description: "My personal thoughts on the web and programming."
    config:
        order:
            variable: posts
            field: date
            direction: desc

/blog/page-{page}:
    template: blog/overview.twig
    variables:
        title: Blog
        overviewTitle: programming
        posts: src/content/blog.yaml
        meta:
            description: "My personal thoughts on the web and programming."
    config:
        pagination:
            variable: posts
            perPage: 100
            parameter: page
        order:
            variable: posts
            field: date
            direction: desc

/blog/{id}:
    template: blog/detail.twig
    variables:
        overviewTitle: programming
        post: src/content/blog.yaml
        meta:
            description: "My personal thoughts on the web and programming."
    config:
        collection:
            variable: post
            parameter: id
        next: true
        meta: true

/blogs-for-devs:
    template: blog/overview.twig
    variables:
        title: Blogs for Devs
        overviewTitle: Blogs for Devs
        posts: src/content/blogs-for-devs.yaml
        overviewUrl: /blogs-for-devs/00-index
        rssUrl: /blogs-for-devs/rss
        detailUrl: /blogs-for-devs
    config:
        order:
            variable: posts
            field: title
            direction: asc


/blogs-for-devs/{id}:
    template: blog/detail.twig
    variables:
        overviewUrl: /blogs-for-devs/00-index
        rssUrl: /blogs-for-devs/rss
        detailUrl: /blogs-for-devs
        post: src/content/blogs-for-devs.yaml
        meta:
            description: "Podcast reviews — Listen. Critically."
    config:
        collection:
            variable: post
            parameter: id
        next: true

/cookies:
    template: blog/detail.twig
    variables:
        post: src/content/cookies.yaml

/podcasts/all:
    template: blog/overview.twig
    variables:
        detailUrl: /podcasts
        rssUrl: /podcasts/rss
        overviewTitle: podcasts
        title: Podcasts
        posts: src/content/podcasts.yaml
        meta:
            description: "Podcast reviews — Listen. Critically."

/podcasts/{id}:
    template: blog/detail.twig
    variables:
        overviewUrl: /podcasts/all
        rssUrl: /podcasts/rss
        detailUrl: /podcasts
        post: src/content/podcasts.yaml
        meta:
            description: "Podcast reviews — Listen. Critically."
    config:
        collection:
            variable: post
            parameter: id
        next: true

/games/all:
    template: blog/overview.twig
    variables:
        detailUrl: /games
        rssUrl: /games/rss
        overviewTitle: games
        title: Games
        posts: src/content/games.yaml
        meta:
            description: "Anything game related crossing my path"

/games/{id}:
    template: blog/detail.twig
    variables:
        overviewUrl: /games/all
        rssUrl: /games/rss
        detailUrl: /games
        post: src/content/games.yaml
    config:
        collection:
            variable: post
            parameter: id
        next: true

/newsletter/success:
    template: newsletter/success.twig
    variables:
        title: Stitcher Mail
        meta:
            description: Subscribe to Stitcher Mail!

/newsletter/pending:
    template: newsletter/pending.twig
    variables:
        title: Stitcher Mail
        meta:
            description: Subscribe to Stitcher Mail!

/newsletter/unsub:
    template: newsletter/unsub.twig
    variables:
        title: Stitcher Mail
        meta:
            description: Subscribe to Stitcher Mail!

/newsletter/subscribe:
    template: newsletter/index.twig
    variables:
        title: Stitcher Mail
        meta:
            description: Subscribe to Stitcher Mail!

/laravel-beyond-crud:
    template: blog/overview_tag.twig
    variables:
        title: Laravel beyond CRUD
        posts: src/content/blog.yaml
        meta:
            description: "A blog series about managing larger Laravel projects"
    config:
        order:
            variable: posts
            field: date
            direction: asc
        filter:
            posts:
                book: true

/php-74:
    template: blog/overview_tag.twig
    variables:
        title: PHP 7.4
        posts: src/content/blog.yaml
        intro: src/content/intro/php-74.md
        meta:
            description: "Short closures, typed properties, preloading and more"
    config:
        order:
            variable: posts
            field: date
            direction: desc
        filter:
            posts:
                tag: php-74

/favicon:
    template: favicon.twig
